LOC_SCENES = {
    "dark_forest": "🌲🌫🕸️\n🌳🌳🌳🌳🌳\n🌳🌑👁🌑🌳\n🌳🌳💀🌳🌳\n🌿🌿🐍🌿🌿",
    "riverbank": "🌊🌊🌊🌊🌊\n🪨🐟🌊🐟🪨\n🌊🌀🌊🌊🌊\n🪨🪨🪨🪨🪨\n🎣🏚️🌿🌿🌿",
    "ancient_ruins": "🏛️💎🏛️💎🏛️\n🪨📜⚡📜🪨\n🏛️🔮👁🔮🏛️\n🪨🗿🗿🗿🪨\n🌿🏛️🌿🏛️🌿",
    "wolf_den": "🦴🐺🦴🐺🦴\n🐺👁🔴👁🐺\n🩸🦴🩸🦴🩸\n🐺🔥🔥🔥🐺\n🦴🐺🩸🐺🦴",
    "fishing_village": "🏘️🎣🌊🌊🌊\n🚣🐟🪵🪵🪵\n🪵🧓🪝🪵🪵\n🪵🔥🐟🪵🪵\n⚓🪵🪵🪵🏚️",
    "market_square": "🎪💎🧪📜🔮\n🪙⚖️🏺🪙⚖️\n🎭🪙💎🪙🎭\n🎪🪙🪙🪙🎪\n🪙🪙🪙🪙🪙",
    "library_of_echoes": "📚📜📚📜📚\n📖👁📖👁📖\n📚🔮📖🔮📚\n📖👻📖👻📖\n📚✨📖✨📚",
    "obsidian_tower": "🖤🗼🖤🗼🖤\n🖤⚡👁⚡🖤\n🖤🔥🗼🔥🖤\n🖤🗿🖤🗿🖤\n🖤🖤🕸️🖤🖤",
    "blood_meadow": "🩸🌿🩸🌿🩸\n🌿🩸🩸🩸🌿\n🩸🌳💀🌳🩸\n🌿🩸👁🩸🌿\n🩸🌿🩸🌿🩸",
    "white_forest": "🤍❄️🤍❄️🤍\n🤍🦴🤍🦴🤍\n🤍👻🤍👻🤍\n🤍❄️🤍❄️🤍\n🤍🤍🤍🤍🤍",
    "underwater_cave": "🌊🫧🌊🫧🌊\n🪸🐙🪸🐙🪸\n🌊👁🌊👁🌊\n🪸🦷🪸🦷🪸\n🌊🫧🌊🫧🌊",
    "temple_of_shadows": "🖤🏛️🖤🏛️🖤\n🖤🔪🌑🖤\n🖤🗿👁🗿🖤\n🖤🕯️🖤🕯️🖤\n🖤🖤🖤🖤🖤",
    "mirror_hall": "🪞✨🪞✨🪞\n🪞👁🪞👁🪞\n🪞💭🪞💭🪞\n🪞⚡🪞⚡🪞\n🪞✨🪞✨🪞",
    "tower_summit": "👁🗼👁🗼👁\n☁️☁️☁️☁️☁️\n⚡🔮⚡🔮⚡\n☁️☁️☁️☁️☁️\n🗼👁🗼👁🗼",
    "frozen_lake": "🧊❄️🧊❄️🧊\n🧊👁🧊👁🧊\n❄️💀🧊💀❄️\n🧊💙🧊💙🧊\n🧊❄️🧊❄️🧊",
    "sunken_throne": "🌊👑🌊👑🌊\n🪸💀🪸💀🪸\n🌊💍🌊💍🌊\n🪸⚓🪸⚓🪸\n🌊🫧🌊🫧🌊",
    "void_gate": "🕳️⬛🕳️⬛🕳️\n⬛👁⬛👁⬛\n🕳️⚡⬛⚡🕳️\n⬛🖤⬛🖤⬛\n🕳️⬛🕳️⬛🕳️",
    "heart_of_mist": "💜🌀💜🌀💜\n🌀👁💜👁🌀\n💜🌀💜🌀💜\n🌀💀💜💀🌀\n💜🌀💜🌀💜",
    "witch_swamp": "🟢🫧🟢🫧🟢\n🫧🐸🟢🐸🫧\n🟢🧪🫧🧪🟢\n🫧👁🟢👁🫧\n🟢🫧🫧🫧🟢",
    "forgotten_graveyard": "🪦💀🪦💀🪦\n💀🕯️🪦🕯️💀\n🪦👻💀👻🪦\n💀⚰️🪦⚰️💀\n🪦💀🪦💀🪦",
    "crystal_cave": "💎🔮💎🔮💎\n🔮💠💎💠🔮\n💎✨🔮✨💎\n🔮💠💎💠🔮\n💎🔮💎🔮💎",
    "dark_harbour": "⚓🚢🌊🌊🌊\n🌊🦴🚢🦴🌊\n🫧👻🌊👻🫧\n🌊🕸️🚢🕸️🌊\n⚓🌊🌊🌊🌊",
    "ash_fields": "🔥🌫🔥🌫🔥\n🌫💀🔥💀🌫\n🔥🌫🔥🌫🔥\n🌫🪙🔥🪙🌫\n🔥🌫🔥🌫🔥",
    "shadow_market": "🎭🖤🎭🖤🎭\n🖤💰🎭💰🖤\n🎭🔪🖤🔪🎭\n🖤🎭💰🎭🖤\n🎭🖤🎭🖤🎭",
    "abandoned_mine": "⛏️🪨💎🪨⛏️\n🪨🕸️⛏️🕸️🪨\n💎🕷️💎🕷️💎\n🪨⛏️🪨⛏️🪨\n🪨💀💎💀🪨",
    "enchanted_grove": "🌿✨🌿✨🌿\n✨🌳💜🌳✨\n🌿🍃✨🍃🌿\n✨🧚🌿🧚✨\n🌿✨🌿✨🌿",
    "abandoned_camp": "⛺🔥🌫🌫🌫\n🪵🐾🪵🐾🪵\n🌫👁🪵👁🌫\n🪵🎒🪵🎒🪵\n🌫🔥🌫🌫🌫",
    "portal_nexus": "🌀💜🌀💜🌀\n💜⚡🌀⚡💜\n🌀🖤💜🖤🌀\n💜🌀🌀🌀💜\n🌀💜🌀💜🌀",
}

CREATURE_SCENES = {
    "wolf_alpha": "🐺👁🔥👁🐺\n🩸🐺🐺🐺🩸",
    "wolf_pack": "🐺🐺🐺🐺🐺\n🦴🩸🦴🩸🦴",
    "shadow_stalker": "👁‍🗨️🌑🖤🌑👁‍🗨️\n🌑💀🖤💀🌑",
    "river_serpent": "🐍🌊👁🌊🐍\n🌊🐍🐍🐍🌊",
    "elder_fisherman": "🧓🎣🌊🌊🌊\n🐟🪝🪵🪵🪵",
    "echo_wraith": "👻📖👁📖👻\n📖💬📖💬📖",
    "gargoyle": "🗿👁⚡👁🗿\n🖤🗿🗼🗿🖤",
    "blood_tree": "🌳🩸🌳🩸🌳\n🩸🩸💀🩸🩸",
    "frost_spirit": "❄️👻❄️👻❄️\n🧊👁🧊👁🧊",
    "mirror_copy": "🪞👤🪞👤🪞\n👤🪞👁🪞👤",
    "the_keeper": "👁🖤👁🖤👁\n🖤🗼👁🗼🖤",
    "dead_king": "👑💀👑💀👑\n💀⚰️👑⚰️💀",
    "void_walker": "🕳️👁🕳️👁🕳\n🖤🌀⬛🌀🖤",
    "swamp_witch": "🧙‍♀️🟢🧪🟢🧙‍♀️\n🟢🐸👁🐸🟢",
    "bogey": "🫧🟢🫧🟢🫧\n🟢👁🟢👁🟢",
    "grave_sentinel": "💀⚔️💀⚔️💀\n🪦🛡️💀🛡️🪦",
    "crystal_golem": "💎🗿💎🗿💎\n💠👁💠👁💠",
    "harbour_ghost": "👻⚓👻⚓👻\n🌊👁🌊👁🌊",
    "ash_wraith": "🔥👻🔥👻🔥\n🌫💀🌫💀🌫",
    "skeleton_mage": "💀🔮💀🔮💀\n🦴⚡🦴⚡🦴",
    "kraken_tentacle": "🐙🌊🐙🌊🐙\n🌊👁🌊👁🌊",
    "mine_crawler": "🕷️⛏️🕷️⛏️🕷\n🕸️👁🕸️👁🕸",
    "crystal_spider": "💎🕷️💎🕷️💎\n🕸️💠🕸️💠🕸",
    "grove_sprite": "🧚✨🧚✨🧚\n✨🌿💫🌿✨",
    "ancient_warden": "🗿🌿🗿🌿🗿\n🌿👁🌿👁🌿",
    "camp_stalker": "👁🌫👁🌫👁\n🌫🐾🌫🐾🌫",
    "portal_phantom": "🌀👁🌀👁🌀\n💜🖤💜🖤💜",
}

SCENE_DIVIDER = "┈┈┈┈┈┈┈┈┈┈┈┈┈┈"
SCENE_DIVIDER_THIN = "┄┄┄┄┄┄┄┄┄┄┄┄┄┄"
