WORLD_EVENT_DEFS = {
    "forest_fire": {
        "name": "Лесной пожар",
        "icon": "🔥",
        "description": "Пламя пожирает деревья. Дым виден за лигов.",
        "probability": 0.04,
        "duration_days": 3,
        "regions": ["dark_forest"],
        "effects": {"tree_density": -40, "creature_count": -20, "danger_level": 15},
        "chain_events": ["refugees", "wood_scarcity"],
        "chain_delay_days": 2,
        "is_legendary": False,
    },
    "wolf_pack_migration": {
        "name": "Миграция волков",
        "icon": "🐺",
        "description": "Огромная стая волков движется через лес. Они голодны.",
        "probability": 0.06,
        "duration_days": 5,
        "regions": ["dark_forest"],
        "effects": {"creature_count": 30, "danger_level": 10},
        "chain_events": ["village_attack"],
        "chain_delay_days": 3,
        "is_legendary": False,
    },
    "harvest_festival": {
        "name": "Праздник урожая",
        "icon": "🌾",
        "description": "Жители празднуют сбор урожая. Пахнет хлебом и специями.",
        "probability": 0.08,
        "duration_days": 2,
        "regions": ["civilization"],
        "effects": {"food_supply": 20, "wealth": 10},
        "chain_events": [],
        "is_legendary": False,
    },
    "drought": {
        "name": "Засуха",
        "icon": "☀️",
        "description": "Солнце палит без пощады. Реки мелеют. Трава сохнет.",
        "probability": 0.03,
        "duration_days": 7,
        "regions": ["coast", "civilization"],
        "effects": {"food_supply": -30, "danger_level": 5},
        "chain_events": ["famine", "bandits"],
        "chain_delay_days": 4,
        "is_legendary": False,
    },
    "ancient_altar_discovered": {
        "name": "Обнаружен древний алтарь",
        "icon": "🔮",
        "description": "Среди руин пробудился алтарь. Он зовёт.",
        "probability": 0.02,
        "duration_days": 0,
        "regions": ["mountains"],
        "effects": {"magic_level": 20},
        "chain_events": ["cult_appears"],
        "chain_delay_days": 3,
        "is_legendary": True,
    },
    "merchant_caravan": {
        "name": "Торговый караван",
        "icon": "🐫",
        "description": "Караван с товарами прибыл. Торговцы раскупоривают мешки.",
        "probability": 0.10,
        "duration_days": 2,
        "regions": ["civilization", "coast"],
        "effects": {"wealth": 15},
        "chain_events": [],
        "is_legendary": False,
    },
    "plague": {
        "name": "Эпидемия",
        "icon": "☠️",
        "description": "Болезнь распространяется. Люди падают замертво.",
        "probability": 0.02,
        "duration_days": 10,
        "regions": ["civilization"],
        "effects": {"population": -20, "danger_level": 10},
        "chain_events": ["healer_quest"],
        "chain_delay_days": 2,
        "is_legendary": True,
    },
    "flood": {
        "name": "Наводнение",
        "icon": "🌊",
        "description": "Вода поднимается. Затопляет дома и дороги.",
        "probability": 0.04,
        "duration_days": 4,
        "regions": ["coast"],
        "effects": {"food_supply": -25, "tree_density": -15, "danger_level": 10},
        "chain_events": ["refugees"],
        "chain_delay_days": 1,
        "is_legendary": False,
    },
    "wandering_merchant": {
        "name": "Странствующий торговец",
        "icon": "🎭",
        "description": "Загадочный человек с товарами из далёких земель.",
        "probability": 0.12,
        "duration_days": 1,
        "regions": None,
        "effects": {},
        "chain_events": [],
        "is_legendary": False,
    },
    "meteorite": {
        "name": "Метеорит",
        "icon": "☄️",
        "description": "Огненный шар рушится с неба. Земля содрогается.",
        "probability": 0.01,
        "duration_days": 0,
        "regions": None,
        "effects": {"magic_level": 30, "danger_level": 20},
        "chain_events": ["crater_resources"],
        "chain_delay_days": 5,
        "is_legendary": True,
    },
    "lantern_festival": {
        "name": "Праздник огней",
        "icon": "🏮",
        "description": "Тысячи фонарей поднимаются в небо. Магия наполняет воздух.",
        "probability": 0.06,
        "duration_days": 1,
        "regions": ["civilization"],
        "effects": {"magic_level": 10, "danger_level": -5},
        "chain_events": [],
        "is_legendary": False,
    },
    "fog_storm": {
        "name": "Туманный шторм",
        "icon": "🌫️",
        "description": "Густой туман накрывает землю. Видимость — ноль.",
        "probability": 0.05,
        "duration_days": 2,
        "regions": ["dark_forest", "mountains"],
        "effects": {"danger_level": 15},
        "chain_events": [],
        "is_legendary": False,
    },
    "bandits_on_road": {
        "name": "Разбойники на дорогах",
        "icon": "🗡️",
        "description": "Бандиты перекрыли торговые пути.",
        "probability": 0.07,
        "duration_days": 3,
        "regions": ["dark_forest", "civilization"],
        "effects": {"wealth": -10, "danger_level": 10},
        "chain_events": ["guild_patrol"],
        "chain_delay_days": 2,
        "is_legendary": False,
    },
    "good_harvest": {
        "name": "Хороший урожай",
        "icon": "🌿",
        "description": "Щедрый сезон. Запасы пополняются.",
        "probability": 0.10,
        "duration_days": 3,
        "regions": ["civilization", "coast"],
        "effects": {"food_supply": 25},
        "chain_events": [],
        "is_legendary": False,
    },
    "ruin_anomaly": {
        "name": "Аномалия в руинах",
        "icon": "⚡",
        "description": "Из руин исходит странное свечение. Камни вибрируют.",
        "probability": 0.03,
        "duration_days": 2,
        "regions": ["mountains"],
        "effects": {"magic_level": 15},
        "chain_events": ["artifact_found"],
        "chain_delay_days": 4,
        "is_legendary": False,
    },
    "clan_war": {
        "name": "Война кланов",
        "icon": "⚔️",
        "description": "Два клана сошлись в смертельной битве.",
        "probability": 0.02,
        "duration_days": 5,
        "regions": ["civilization"],
        "effects": {"population": -10, "danger_level": 25},
        "chain_events": ["refugees", "bandits"],
        "chain_delay_days": 2,
        "is_legendary": True,
    },
    "ship_in_harbour": {
        "name": "Корабль в гавани",
        "icon": "🚢",
        "description": "Неизвестный корабль причалил. Экипаж ищет экипаж.",
        "probability": 0.04,
        "duration_days": 2,
        "regions": ["coast"],
        "effects": {"wealth": 20},
        "chain_events": ["sea_trade"],
        "chain_delay_days": 3,
        "is_legendary": False,
    },
    "undead_awakening": {
        "name": "Пробуждение мертвецов",
        "icon": "💀",
        "description": "Мертвецы поднимаются из могил. Кладбище оживает.",
        "probability": 0.02,
        "duration_days": 4,
        "regions": ["dark_forest"],
        "effects": {"danger_level": 30, "creature_count": 15},
        "chain_events": ["graveyard_siege"],
        "chain_delay_days": 3,
        "is_legendary": True,
    },
    "spring_bloom": {
        "name": "Весеннее цветение",
        "icon": "🌸",
        "description": "Цветы распускаются повсюду. Мир наполняется жизнью.",
        "probability": 0.12,
        "duration_days": 3,
        "regions": None,
        "effects": {"food_supply": 15, "magic_level": 5},
        "chain_events": [],
        "is_legendary": False,
    },
    "refugees": {
        "name": "Беженцы",
        "icon": "🏃",
        "description": "Толпы беженцев ищут укрытие. Они несут горе и слёзы.",
        "probability": 0.0,
        "duration_days": 3,
        "regions": ["civilization"],
        "effects": {"population": 10, "food_supply": -10},
        "chain_events": [],
        "is_legendary": False,
        "is_chain_only": True,
    },
    "wood_scarcity": {
        "name": "Нехватка древесины",
        "icon": "🪵",
        "description": "Древесина стала дефицитом. Цены растут.",
        "probability": 0.0,
        "duration_days": 5,
        "regions": ["civilization"],
        "effects": {"wealth": -10},
        "chain_events": [],
        "is_legendary": False,
        "is_chain_only": True,
    },
    "village_attack": {
        "name": "Нападение на деревню",
        "icon": "🏚️",
        "description": "Волки напали на деревню. Стены разрушены.",
        "probability": 0.0,
        "duration_days": 2,
        "regions": ["civilization"],
        "effects": {"population": -15, "danger_level": 15, "wealth": -15},
        "chain_events": ["refugees"],
        "chain_delay_days": 1,
        "is_legendary": False,
        "is_chain_only": True,
    },
    "famine": {
        "name": "Голод",
        "icon": "🍽️",
        "description": "Еды нет. Люди едят кору деревьев.",
        "probability": 0.0,
        "duration_days": 7,
        "regions": ["civilization"],
        "effects": {"food_supply": -20, "population": -10},
        "chain_events": ["bandits"],
        "chain_delay_days": 3,
        "is_legendary": False,
        "is_chain_only": True,
    },
    "bandits": {
        "name": "Бандиты",
        "icon": "🏴",
        "description": "Голодные люди превращаются в разбойников.",
        "probability": 0.0,
        "duration_days": 4,
        "regions": ["civilization", "dark_forest"],
        "effects": {"danger_level": 15, "wealth": -10},
        "chain_events": [],
        "is_legendary": False,
        "is_chain_only": True,
    },
    "cult_appears": {
        "name": "Появился культ",
        "icon": "🕯️",
        "description": "Тёмный культ собирает последователей у алтаря.",
        "probability": 0.0,
        "duration_days": 7,
        "regions": ["mountains"],
        "effects": {"danger_level": 20, "magic_level": 15},
        "chain_events": [],
        "is_legendary": False,
        "is_chain_only": True,
    },
    "healer_quest": {
        "name": "Ищется целитель",
        "icon": "💚",
        "description": "Болезнь обрела масштаб. Нужен герой.",
        "probability": 0.0,
        "duration_days": 5,
        "regions": ["civilization"],
        "effects": {},
        "chain_events": [],
        "is_legendary": False,
        "is_chain_only": True,
    },
    "crater_resources": {
        "name": "Ресурсы в кратере",
        "icon": "💎",
        "description": "В кратере от метеорита обнаружены редкие кристаллы.",
        "probability": 0.0,
        "duration_days": 5,
        "regions": None,
        "effects": {"wealth": 25, "magic_level": 10},
        "chain_events": [],
        "is_legendary": False,
        "is_chain_only": True,
    },
    "guild_patrol": {
        "name": "Патруль гильдии",
        "icon": "🛡️",
        "description": "Гильдия выслала патруль для очистки дорог.",
        "probability": 0.0,
        "duration_days": 3,
        "regions": ["civilization", "dark_forest"],
        "effects": {"danger_level": -10},
        "chain_events": [],
        "is_legendary": False,
        "is_chain_only": True,
    },
    "artifact_found": {
        "name": "Найден артефакт",
        "icon": "🏺",
        "description": "Среди аномалии обнаружен древний артефакт.",
        "probability": 0.0,
        "duration_days": 0,
        "regions": ["mountains"],
        "effects": {"wealth": 30},
        "chain_events": [],
        "is_legendary": False,
        "is_chain_only": True,
    },
    "sea_trade": {
        "name": "Морская торговля",
        "icon": "⚓",
        "description": "Корабль открыл новый торговый маршрут.",
        "probability": 0.0,
        "duration_days": 5,
        "regions": ["coast"],
        "effects": {"wealth": 15, "food_supply": 10},
        "chain_events": [],
        "is_legendary": False,
        "is_chain_only": True,
    },
    "graveyard_siege": {
        "name": "Осада кладбища",
        "icon": "⚰️",
        "description": "Нежить штурмует кладбище. Сражение за покой мёртвых.",
        "probability": 0.0,
        "duration_days": 3,
        "regions": ["dark_forest"],
        "effects": {"danger_level": 20, "creature_count": 10},
        "chain_events": [],
        "is_legendary": False,
        "is_chain_only": True,
    },
}


def get_random_events(region_id=None, current_day=1, world_pressure=10):
    import random
    candidates = []
    for key, ev in WORLD_EVENT_DEFS.items():
        if ev.get("is_chain_only", False):
            continue
        if ev["probability"] <= 0:
            continue
        if ev.get("regions") and region_id and region_id not in ev["regions"]:
            continue
        if ev.get("min_world_pressure", 0) > world_pressure:
            continue
        candidates.append((key, ev))

    triggered = []
    for key, ev in candidates:
        if random.random() < ev["probability"]:
            triggered.append(key)
    return triggered
