from enum import StrEnum


class EventType(StrEnum):
    COMBAT_VICTORY = "combat_victory"
    COMBAT_DEFEAT = "combat_defeat"
    COMBAT_DRAW = "combat_draw"
    LOCATION_DISCOVERED = "location_discovered"
    LOCATION_VISITED = "location_visited"
    QUEST_ACCEPTED = "quest_accepted"
    QUEST_COMPLETED = "quest_completed"
    ITEM_OBTAINED = "item_obtained"
    ITEM_USED = "item_used"
    ITEM_SOLD = "item_sold"
    ITEM_BOUGHT = "item_bought"
    PLAYER_LEVEL_UP = "player_level_up"
    PLAYER_DEATH = "player_death"
    PLAYER_REVIVE = "player_revive"
    PLAYER_REST = "player_rest"
    NPC_KILLED = "npc_killed"
    NPC_TALKED = "npc_talked"
    PVP_WIN = "pvp_win"
    PVP_LOSS = "pvp_loss"
    PVP_DRAW = "pvp_draw"
    TRADE_COMPLETED = "trade_completed"
    TRADE_CREATED = "trade_created"
    GUILD_CREATED = "guild_created"
    GUILD_JOINED = "guild_joined"
    GUILD_LEFT = "guild_left"
    GUILD_DONATED = "guild_donated"
    CRAFT_COMPLETED = "craft_completed"
    SECRET_FOUND = "secret_found"
    ACHIEVEMENT_UNLOCKED = "achievement_unlocked"
    WORLD_EVENT = "world_event"
    WHISPER = "whisper"
    DAILY_COMPLETED = "daily_completed"
    EQUIPMENT_CHANGED = "equipment_changed"
    NEW_USER = "new_user"
    REPUTATION_CHANGED = "reputation_changed"
    PLAYER_RENAMED = "player_renamed"
    LEGEND_DISCOVERED = "legend_discovered"
    NPC_TRADED = "npc_traded"
    NPC_GREETED = "npc_greeted"
    ECONOMY_TRANSACTION = "economy_transaction"
    GUILD_ROLE_CHANGED = "guild_role_changed"


class Importance(StrEnum):
    TRIVIAL = "trivial"
    COMMON = "common"
    NOTABLE = "notable"
    RARE = "rare"
    LEGENDARY = "legendary"
